const Q={
strategic:['Experiência prévia no setor e como empreendedor?','Possui software de gestão integrado plenamente implantado?','Gestores e colaboradores conhecem os objetivos e metas da empresa?','A empresa avalia resultados por indicadores, metas ou objetivos?','Possui Visão, Missão, Valores, fatores-chave de sucesso e competências críticas descritos?'],
financial:['O responsável possui conhecimento técnico ou experiência prévia na área?','O setor possui software específico de gestão financeira?','Controla as contas a pagar?','Controla as contas a receber?','Realiza conciliação bancária regularmente?','Controla o caixa físico?','Conhece o faturamento bruto mensal?','Possui e analisa fluxo de caixa?','Possui e analisa DRE gerencial mensal?'],
marketing:['O gestor possui conhecimento técnico ou experiência em marketing?','Possui software específico de gestão comercial ou de mercado?','Possui cadastro de clientes estruturado e utilizado?','Analisa clientes por importância, frequência ou volume?','Utiliza meios de propaganda e comunicação?','Conhece os concorrentes diretos e indiretos?','Acompanha indicadores de vendas?','Possui estratégias claras de prospecção de clientes?','Pesquisa a satisfação dos clientes?','Dá tratamento às reclamações de clientes?'],
production:['Há gestor do processo produtivo capacitado ou experiente?','Controla ferramentas e equipamentos?','Controla o processo produtivo?','Conhece os custos de produção ou do serviço?','Avalia indicadores de produtividade, capacidade, perdas ou retrabalho?','Planeja a produção conforme a demanda de vendas?','Utiliza tecnologia de automação na produção?'],
purchases:['O gestor de compras possui conhecimento técnico ou experiência?','Cadastra e avalia fornecedores?','As regras de compras estão descritas?','Existe documento formal para solicitação de compras?','Conhece e controla o tempo de reposição de estoque?','Controla o índice de perdas no estoque?','Realiza inventário de estoque?','Controla a validade dos produtos, quando aplicável?'],
distribution:['O gestor de distribuição possui conhecimento ou experiência?','Controla os canais de distribuição?','Controla frota e quilometragem?','Controla expedição e entregas?','Acompanha prazos de entrega ou conclusão de serviços?','Possui estratégia de gestão de logística interna?','Controla e analisa o recebimento de fornecedores?'],
quality:['O responsável pela qualidade possui conhecimento ou experiência?','Atende à legislação específica de qualidade aplicável?','O pessoal conhece sua contribuição para os objetivos da qualidade?','Possui procedimentos formais para atividades e setores?','Há ações formalizadas para não conformidades e anomalias?','Controla a qualidade de matéria-prima, produto ou serviço?','Avalia resultados de qualidade por indicadores?','Compartilha resultados de qualidade com todas as áreas?'],
people:['O responsável por RH possui conhecimento ou experiência?','Possui software específico para gestão de pessoas?','Possui descrição de cargos?','Realiza recrutamento e seleção?','Integra e treina novos funcionários?','Realiza treinamentos de capacitação?','Controla indicadores de pessoas?','Analisa criticamente dados da folha de pagamento?','Pratica remuneração variável ou por desempenho?'],
innovation:['Há responsável, equipe ou rotina para identificar oportunidades de inovação?','Acompanha tendências, clientes e tecnologias relevantes ao setor?','Utiliza ferramentas digitais para apoiar gestão, atendimento, vendas ou processos?','Registra e acompanha ideias de melhoria de colaboradores, clientes ou parceiros?','Realiza testes ou pilotos antes de implantar novidades?','Possui indicadores ou metas para iniciativas de inovação e tecnologia?','Adota práticas de segurança, backup e controle de acesso aos dados?','Capacita colaboradores para usar tecnologias e novos processos?']};
const N={strategic:'Estratégica',financial:'Econômico-financeira',marketing:'Marketing e comercial',production:'Produção',purchases:'Compras e estoque',distribution:'Distribuição',quality:'Qualidade',people:'Gestão de pessoas',innovation:'Inovação e tecnologias aplicadas'}, IDS=Object.keys(Q),V={no:0,partial:1/3,yes:1},K='sondagem-empresarial-v3';
let S=JSON.parse(localStorage.getItem(K)||'null')||{selected:IDS,answers:{},notes:{},evidence:{},company:'',revenue:''},i=0;
const $=id=>document.getElementById(id),save=()=>localStorage.setItem(K,JSON.stringify(S)),sel=()=>IDS.filter(x=>S.selected.includes(x)),key=(d,j)=>d+':'+j,esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
function score(d){let a=Q[d].map((_,j)=>S.answers[key(d,j)]).filter(x=>x&&x!=='na').map(x=>V[x]);return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
function ops(){let a=sel().filter(x=>['production','purchases','distribution'].includes(x)).map(score);if(!a.length)return null;if(a.length<3)return a.reduce((x,y)=>x+y,0)/a.length;let[x,y,z]=a,n=x>0&&y>0&&z>0?3:x>0&&(y>0||z>0)?2:y>0&&(x>0||z>0)?2:1;return a.reduce((p,c)=>p+c,0)/n}
function areas(){let a=sel().filter(x=>!['production','purchases','distribution'].includes(x)).map(x=>[N[x],score(x),x]),o=ops();if(o!==null)a.splice(3,0,['Operações',o,'operations']);return a}
function renderChoices(){$('dimensionChoices').innerHTML=IDS.map(x=>`<label><input type="checkbox" data-d="${x}" ${S.selected.includes(x)?'checked':''}>${N[x]}</label>`).join('');document.querySelectorAll('[data-d]').forEach(x=>x.onchange=e=>{let d=e.target.dataset.d;S.selected=e.target.checked?[...new Set([...S.selected,d])]:S.selected.filter(x=>x!==d);if(!S.selected.length){S.selected=[d];e.target.checked=true}i=0;save();render()})}
function render(){renderChoices();let ds=sel();if(!ds.length){$('stepper').innerHTML='';$('survey').innerHTML='<p class="note">Selecione ao menos uma dimensão para iniciar a sondagem.</p>';$('next').classList.add('hidden');$('showDashboard').classList.add('hidden');return}i=Math.min(i,ds.length-1);$('stepper').innerHTML=ds.map((d,j)=>`<button class="step ${j===i?'active':''}" data-step="${j}">${j+1}. ${N[d]}</button>`).join('');document.querySelectorAll('[data-step]').forEach(x=>x.onclick=()=>{i=+x.dataset.step;render()});let d=ds[i],done=Q[d].filter((_,j)=>S.answers[key(d,j)]).length;$('survey').innerHTML=`<div class="dimension-head"><div><p class="eyebrow">Dimensão ${i+1} de ${ds.length}${ds.length<IDS.length?' · diagnóstico parcial':''}</p><h2>${N[d]}</h2><p>Selecione uma resposta por pergunta e registre evidências ou observações quando necessário.</p></div><div class="progress">${done}/${Q[d].length} respondidas</div></div><div class="questions">${Q[d].map((q,j)=>question(d,q,j)).join('')}</div>`;document.querySelectorAll('input[type=radio]').forEach(x=>x.onchange=e=>{S.answers[e.target.name]=e.target.value;save();render()});document.querySelectorAll('textarea').forEach(x=>x.oninput=e=>{let[t,...z]=e.target.dataset.f.split(':');S[t][z.join(':')]=e.target.value;save()});$('previous').disabled=!i;$('next').classList.toggle('hidden',i===ds.length-1);$('showDashboard').classList.toggle('hidden',i!==ds.length-1)}
function question(d,q,j){let k=key(d,j),a=S.answers[k]||'';return `<article class="question"><div class="question-text"><span class="question-number">${j+1}.</span>${esc(q)}</div><div class="options">${[['no','Não'],['partial','Parcial'],['yes','Sim'],['na','Não se aplica']].map(([v,n])=>`<label><input type="radio" name="${k}" value="${v}" ${a===v?'checked':''}><span>${n}</span></label>`).join('')}</div><div class="details"><label>Evidências<textarea data-f="evidence:${k}">${esc(S.evidence[k])}</textarea></label><label>Observações<textarea data-f="notes:${k}">${esc(S.notes[k])}</textarea></label></div></article>`}
function can(id){let c=$(id),r=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*r;c.height=h*r;let x=c.getContext('2d');x.scale(r,r);x.clearRect(0,0,w,h);return[x,w,h]}
function line(data){let[x,w,h]=can('maturityChart'),l=42,r=14,t=18,b=58,cw=w-l-r,ch=h-t-b;x.font='12px Arial';for(let z=0;z<=10;z++){let y=t+ch-ch*z/10;x.strokeStyle='#d6dee6';x.beginPath();x.moveTo(l,y);x.lineTo(l+cw,y);x.stroke();x.fillStyle='#607182';x.textAlign='right';x.fillText(z*10+'%',l-7,y+4)}[['#19a99d',d=>d.v,7],['#f3aa38',d=>.5,4],['#6253b8',d=>.8,4]].forEach(([c,f,z])=>{x.strokeStyle=c;x.lineWidth=z;let open=false;x.beginPath();data.forEach((d,j)=>{if(!d.on){open=false;return}let px=l+cw*(j+.5)/data.length,py=t+ch*(1-f(d));if(open)x.lineTo(px,py);else{x.moveTo(px,py);open=true}});x.stroke()});x.fillStyle='#34495e';x.textAlign='center';data.forEach((d,j)=>x.fillText(d.n,l+cw*(j+.5)/data.length,t+ch+18))}
function radar(data){let[x,w,h]=can('radarChart'),cx=w/2,cy=h/2,r=Math.min(w,h)*.34,n=data.length,p=(j,v)=>[cx+Math.cos(-Math.PI/2+j*2*Math.PI/n)*r*v,cy+Math.sin(-Math.PI/2+j*2*Math.PI/n)*r*v];for(let z=1;z<=5;z++){x.strokeStyle='#d6dee6';x.beginPath();for(let j=0;j<n;j++){let[a,b]=p(j,z/5);j?x.lineTo(a,b):x.moveTo(a,b)}x.closePath();x.stroke()}data.forEach((d,j)=>{let[a,b]=p(j,1),[u,v]=p(j,1.16);x.strokeStyle='#d6dee6';x.beginPath();x.moveTo(cx,cy);x.lineTo(a,b);x.stroke();x.fillStyle='#34495e';x.textAlign=u<cx?'right':'left';x.fillText(d.n,u,v)});let first=data.findIndex(d=>d.on);if(first>=0){x.beginPath();data.forEach((d,j)=>{if(d.on){let[a,b]=p(j,d.v);x.lineTo(a,b)}});let[a,b]=p(first,data[first].v);x.lineTo(a,b);x.fillStyle='#19a99d55';x.fill();x.strokeStyle='#168a83';x.stroke()}}
function dash(){let a=areas(),part=S.selected.length<IDS.length,g=a.length?a.reduce((x,y)=>x+y[1],0)/a.length:0;$('dashboardCompany').textContent=S.company||'Empresa não informada';$('partialBadge').classList.toggle('hidden',!part);$('scoreGrid').innerHTML=a.map(x=>`<article class="score"><span>${x[0]}</span><strong>${Math.round(x[1]*100)}%</strong></article>`).join('');$('totalHours').textContent=part?'—':hours(g);$('totalTurns').textContent=part?'Diagnóstico parcial':hours(g)/4+' turnos de 4 horas';$('maturityText').textContent=part?'Resultado parcial: somente as dimensões selecionadas foram consideradas. As não selecionadas aparecem em branco nos gráficos.':'Diagnóstico completo consolidado.';$('areaTurns').innerHTML=a.filter(x=>['financial','marketing','people','operations'].includes(x[2])).map(x=>`<div class="area-turn"><span>${x[0]}</span><strong>${hours(x[1],x[2])} h</strong></div>`).join('');$('dashboard').classList.remove('hidden');let d=IDS.map(x=>({n:N[x],v:score(x),on:S.selected.includes(x)}));line(d);radar(d);$('dashboard').scrollIntoView({behavior:'smooth'})}
function hours(s,k='total'){if(s>=.95)return 0;let m=+(String(S.revenue).replace(/\D/g,''))<36000001,t=m?{total:[172,152,132],financial:[56,48,40],marketing:[56,48,40],people:[56,48,40],operations:[56,48,40]}:{total:[236,216,196],financial:[96,88,80],marketing:[96,88,80],people:[96,88,80],operations:[96,88,80]};return t[k][s<=.5?0:s<=.8?1:2]}
$('companyName').value=S.company;$('annualRevenue').value=S.revenue;$('companyName').oninput=e=>{S.company=e.target.value;save()};$('annualRevenue').oninput=e=>{S.revenue=e.target.value;save()};$('selectAll').onclick=()=>{S.selected=IDS;i=0;save();render()};$('clearSelection').onclick=()=>{S.selected=[];renderChoices()};$('previous').onclick=()=>{if(i){i--;render()}};$('next').onclick=()=>{if(i<sel().length-1){i++;render()}};$('showDashboard').onclick=dash;$('printDashboard').onclick=()=>print();$('newAssessment').onclick=()=>{if(confirm('Deseja iniciar uma nova sondagem?')){localStorage.removeItem(K);S={selected:IDS,answers:{},notes:{},evidence:{},company:'',revenue:''};i=0;render()}};render();
